
//File name JResortCalculator.java
//Written by Ernest Mushinge
//Written on 4/10/15

package JResortCalculator;
//This program is for a resort, the base price for a room is $200, and a guest
//can choose from several options. Reserving a room for a weekend night adds $100
// to the price, including breakfast adds $20, and including a weekend night adds $100 to the price
//including breakfast adds $20, and including a round of golf adds $75. A guest can select non, some,
//or all of these premium additions. Each time the user changes the option package, the price is recalculated.
import javax.swing.*;

import java.awt.*;
import java.awt.event.*;


public class JResortCalculator extends JFrame implements ItemListener{
	
	//declare the named constants that hold the base price for a resort room
	//and premium amounts for a week stay, including breakfast and a round of golf.
	//Also include a variable that holds the total price for the stay, and initialize
	//it to the value of the base price. Later, depending on user's selection,
	//premium fees might be added to totalPrice, making it more than BASE_PRICE. 

	final int BASE_PRICE =200;
	final int WEEKEND_PREMIUM =100;
	final int BREAKFAST_PREMIUM = 20;
	final int GOLF_PREMIUM = 75;
	//this will display BASE_PRICE in totalPrice text field
	int totalPrice = BASE_PRICE;
	
	//Declare three JCheckBox objects. Each is labeled with a String that contains
	//a description of the option and the cost of the option. Each JCheckBox starts with
	//unchecked
	
	JCheckBox weekendBox = new JCheckBox("Weekend premium $" + WEEKEND_PREMIUM, false);
	JCheckBox breakfastBox = new JCheckBox("Breakfast $"+ BREAKFAST_PREMIUM, false);
	JCheckBox golfBox = new JCheckBox("Golf $"+ GOLF_PREMIUM, false);
	
	//Include JLabels to hold user instructions and information and a JTextFiled in
	//which to display the total price
	
	JLabel resortLabel = new JLabel("Resort Price Calculater");
	JLabel ePrice = new JLabel("The price for your stay is");
	JTextField totPrice = new JTextField(4);
	JLabel optionExplainLabel = new JLabel("Base price for a room is $" + BASE_PRICE + ".");
	JLabel optionExplainLabel2 = new JLabel("Check the options you want");
	
	//Begin of the JResortCalculator class constructor. Include instructions to set the 
	//title by passing it to the JFrame parent class constructor, to set the default close
	//operation, and to set the layout manager(that lays out the components on the form).
	//Then add all the necessary components to the JFrame
	
	public JResortCalculator()
	{
		//using JFrame's constructor
		super("Resort Price Estimator");
		//Closes the program upon exit
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		//sets the layout of the form
		setLayout(new FlowLayout());
		//adds the check boxes
		add(resortLabel);
		add(optionExplainLabel);
		add(optionExplainLabel2);
		add(weekendBox);
		add(breakfastBox);
		add(golfBox);
		//add(priceLabel);
		add(totPrice);
		
		//Continual with the constructor by setting the text of the totPrice JTextField to display a dollar sign and the totalPrice
		//value. Register a class as a listener for events generated by each of the three JCheckBoxes. Finally, add a closing
		//brace for the constructor
		
		totPrice.setText("$" + totalPrice);
		weekendBox.addItemListener(this);
		breakfastBox.addItemListener(this);
		golfBox.addItemListener(this);
	}
	
	//Begin the itemStateChanged() method that executes when the user checks or not checks a JCheckBox. Use the appropriate 
	//method to determine which JCheckBox is the source of the current ItemEvent and whether the event was generated by selecting
	//a JCheckBox or by not selecting one
	
	public void itemStateChanged(ItemEvent event)
	{
		Object source = event.getSource();
		int select = event.getStateChange();
		
		//Write a nested if statement that tests whether the source is equivalent to the weekendBox, breakfastBox
		//or by default, the golfBox. In each case, depending on whether the item was selected or not selected, add
		// or subtract the corresponding premium fee from the totalPrice. Display the total price in the JTextField
		//, and add a closing curly brace for the method
		
		if(source ==weekendBox)
			if(select == ItemEvent.SELECTED)
				totalPrice += WEEKEND_PREMIUM;
		
			else 
				totalPrice -= WEEKEND_PREMIUM;
		else if(source == breakfastBox)
		{
			if(select == ItemEvent.SELECTED)
				totalPrice += BREAKFAST_PREMIUM;
			else
				totalPrice -= BREAKFAST_PREMIUM;
		}
		
		else if(source == golfBox)
			if(select == ItemEvent.SELECTED)
				totalPrice += GOLF_PREMIUM;
			else
				totalPrice -= GOLF_PREMIUM;
		
		//display the totalPrice in totPrice
		
		totPrice.setText("$" + totalPrice);
				
	}
	
	
	
	//Main Method
	
	public static void main(String[] args) {
		
          JResortCalculator aFrame = new JResortCalculator();
          
          final int WIDTH = 300;
          final int HEIGHT = 200;
          
          aFrame.setSize(WIDTH, HEIGHT);
          aFrame.setVisible(true);
          
		
	}

}
