//File name JFrameWithComponents.java
//Written by Ernest Mushinge
//Written on 4/10/15

package JFrameWithComponents;

//This swing application displays a JFrame that holds a JLabel
//JTextField, and JButton

import javax.swing.*;

import java.awt.*;
import java.awt.event.*;

//java.awt will allow event handling

//JFrameWithComponents is a child class of JFrame
//Next I added functionality to the JButton and JTextField that I created in JFrameWithComponent
public class JAction2 extends JFrame implements ActionListener {

	// This code will create a label, a text field and a button to JFrame
	JLabel label = new JLabel("Enter you name");
	JLabel namePrompt = new JLabel("Enter your name:");
	JTextField field = new JTextField(12);
	JButton button = new JButton("OK");

	// A constructor that set the JFrame title to "Frame with components", and a
	// default close operation
	// to exit the program when JFrame is closed. Set the layout manager. Add
	// the label, field and button

	public JAction2() {

		super("Action");

		setLayout(new FlowLayout());
		add(label);
		add(field);
		add(button);

		// this code will register JAction class as a listener for events
		// generated by either
		// the button or textField

		button.addActionListener(this);
		field.addActionListener(this);

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

	}

	// For every class registered as an Action Listener should have a method
	// called actionPerformer
	// that performs action when an event is registered

	public void actionPerformed(ActionEvent e) {
		//The code below will change the label text to "Thank you" and button to "Done"
		
		//label.setText("Thank you");
		//button.setText("Done");
		
		//It is possible to use the actionEven argument and the getSource() method
		//to determine the source of the event. Using an if statement, you can
		//you can take different actions when the argument represents different sources.
		//for example, you can change the label in the frame to indicate the event's source. 
		
		Object source = e.getSource();
		if(source ==button)
			label.setText("You clicked the button");
		else
			label.setText("You press Enter");
		
	}

}
